import "./globals.css";
import { Inter } from "next/font/google";
import { ConnectKitProvider, ConnectKitButton } from "@/components/connectkit";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Axilar AI Agent",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="flex items-center justify-between px-4 py-4 bg-gray-100 border-b border-gray-200">
      <h1 className="text-xl font-bold text-gray-900">Axilar AI Agent</h1>
      <ConnectKitButton />
    </header>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConnectKitProvider>
          <Header />
          {children}
        </ConnectKitProvider>
      </body>
    </html>
  );
}
